### 应用配置
POST {{host}}/device/apply/19


### 添加设备
POST {{host}}/device/
Content-Type: application/json

{
  "name": "测试-02",
  "useIp": "192.168.1.22",
  "usePort": 542,
  "registerTemplate": {
    "id": 4
  }
}


### 删除设备
DELETE {{host}}/device/14

### 修改设备
PUT {{host}}/device/
Content-Type: application/json

{
  "id": 19,
  "name": "测试-01",
  "useIp": "192.168.1.5",
  "usePort": 508,
  "registerTemplate": {
    "id": 4
  }
}

### 设备
GET {{host}}/device/1

### 设备列表
GET {{host}}/device/list/1/10

### 添加定位器
POST {{host}}/device/locator
Content-Type: application/json

{
  "name":"温度2",
  "slaveId":1,
  "dataType":2,
  "registerBit":-1,
  "registerRange":3,
  "registerOffset":2
}

### 删除定位器
DELETE {{host}}/device/locator/1

### 修改定位器
PUT {{host}}/device/locator
Content-Type: application/json

{
  "id": 1,
  "name": "温度2",
  "slaveId": 1,
  "dataType": 2,
  "registerBit": -1,
  "registerRange": 3,
  "registerOffset": 2
}

### 查看定位器
GET {{host}}/device/locator/1

### 查看定位器列表
GET {{host}}/device/locator/list/1/10

### 添加模板
POST {{host}}/device/template
Content-Type: application/json

{
  "name": "模板1",
  "version": "1",
  "registerLocators": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### 删除模板
DELETE {{host}}/device/template/4

### 修改模板
PUT {{host}}/device/template
Content-Type: application/json

{
  "id": 4,
  "name": "模板1",
  "version": "1",
  "locators": [1, 3]
}

### 查看模板
GET {{host}}/device/template/3

### 查看模板列表
GET {{host}}/device/template/list/1/10
